apiVersion: v1
kind: Service
metadata:
  name: customer-data-service
  namespace: customer-data-ns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: customer-data-app
